function GenSesHTMLDoc(File,title,SavePath)

if ischar(File)
    [~,title,fext]=fileparts(File);
    switch fext
        case '.mat'
            new = load(File);
            ses = new.new;
        case '.xml'
            ses = xml_Interface.XML2SES(xmlread(File));
        otherwise
            error('File type not supported')
    end
elseif isa(File,'ses')
    ses = File;
    if nargin == 1
        title = ['Untitled_',date];
    end
else
    error('Data type not supported')    
end


keys = ses.nodes.keys;
body ={};
if ses.nodes.Count

%#ok<*AGROW>

%### HEAD ###
COMT = ses.comment;
if strcmp(COMT,'PURPOSE OF MY SES')
    COMT = '';
else
    COMT = strrep(char(COMT),char(10),'<br />'); %#ok<CHARTEN>
end

body{end+1} = sprintf('<h1 id="TOP" >%s </h1><p><strong>Published: </strong>%s<br /><br />%s</p>\n',...
    title,datestr(now),COMT);


%### TREE AND GLOBAL DATA ### 

body{end+1} = '<div class="w3-cell-row">';
body{end+1} = '<div class="w3-cell w3-mobile">';
body{end+1} = sprintf('<h3>%s </h3>\n','System Entity Structure');  

body{end+1} = '<div class="clt">';

Node = ses.nodes(keys{1});
body{end+1} = GenTree(0,ses,Node);


body{end+1} = '</div></div>';

body{end+1} = '<div class="w3-cell w3-mobile"; >';

if iscellstr(ses.var)
    body{end+1} = GenTable('SES Variables',{'Name','Value'},ses.var);
end

if iscellstr(ses.Semantic_Conditions)
    body{end+1} = GenTable('Semantic Conditions',{'Condition'},ses.Semantic_Conditions);
end  

if ~isempty(ses.fcn{1}.Filename)
    body{end+1} ='<br /><h3>SES Functions</h3>';
    body{end+1} = GenSESFun(ses.fcn);
end

body{end+1} = '</div></div>';


%### NODES DATA ### 
body{end+1} = '<br /><br /><br /><h1>Tree Nodes </h1>';

for k = 1:ses.nodes.Count
    Node   = ses.nodes(keys{k});
    body{end+1} = GenNodeSec(Node); 
    switch Node.type
        case 'Entity'             
            if iscellstr(Node.attributes)
                body{end+1} = GenTable('Attributes',{'Name','Value'},Node.attributes);
            end        
        case 'Spec'   
            if iscellstr(Node.specrule)
                body{end+1} = GenTable('Specrule',{'Selection','Condition'},Node.specrule);
            end 
        case 'Aspect'
            if iscellstr(Node.coupling)                
                body{end+1} = GenTable('Coupling',{'Source','From Port','Target','To Port'},Node.coupling);
            elseif ischar(Node.coupling)
                body{end+1} = sprintf('<br /><h3>Coupling</h3>\n%s<p>%s</p>\n',Node.coupling);
            end 
            if iscellstr(Node.aspectrule)
                body{end+1} = GenTable('Aspectrule',{'Selection','Condition'},Node.aspectrule);
            end 
        case 'MAspect'
            body{end+1} = sprintf('<br /><h3>Number of Replication</h3>\n%s<p>%s</p>\n',Node.numRep);
            
            if iscellstr(Node.coupling)                
                body{end+1} = GenTable('Coupling',{'Source','From Port','Target','To Port'},Node.coupling);                
            elseif ischar(Node.coupling)
                body{end+1} = sprintf('<br /><h3>Coupling</h3>\n%s<p>%s</p>\n',Node.coupling);
            elseif iscell(Node.coupling)
                for m = 1:numel(Node.coupling)
                    C_TITL = sprintf('Coupling (NumRep == %d)',m);
                    C_DATA = Node.coupling{m};
                    body{end+1} = GenTable(C_TITL,{'Source','From Port','Target','To Port'},C_DATA); 
                end
            end         
    end    
end
end

htmlStr = GenHTMLBody(title,body);

if nargin == 3 && ischar(SavePath)
    fid = fopen(SavePath,'w');
    fprintf(fid,'%s',htmlStr);
    fclose(fid);    
end
web(['text://',htmlStr],'-notoolbar','-new')
end


function str = GenNodeSec(Node)
NAME = Node.name;
PATH = Node.treepath;
TYPE = Node.type;
if strcmp(TYPE,' ')
    TYPE = 'Node';
end
COMT = Node.comment;
if strcmp(COMT,'MY NODE COMMENT') 
    COMT = ''; %Hide Comment
else
    COMT = strrep(char(COMT),char([13,10]),'<br />');
end

str = sprintf('<br /><h2 id="%s">%s (%s)</h2>\n',...
    PATH,NAME,TYPE);
str = sprintf('%s<small><b>Path: </b><a href="#TOP" style="text-decoration: none">%s</a></small><br /><br />\n',str,PATH);
str = sprintf('%s<p>%s</p>\n',str,COMT);
end


function str = GenTable(title,Head,Data)

trow =['<tr>',sprintf('<th>%s</th>',Head{:}),'<tr>'];
%trow ='';
for k = 1:size(Data,1)
    tdata = sprintf('<td>%s</td>',Data{k,:});
    trow = sprintf('%s<tr>\n\t%s\n</tr>\n',trow,tdata);
end

if isempty(k)
    str = sprintf(...
        '<h3>%s</h3>\n<p>\n none\n</p><br />\n',title); 
else
    str = sprintf(...
        '<h3>%s</h3>\n<table>\n%s\n</table><br />\n',title,trow);    
end
end

function str = GenHTMLBody(title,bodycell)
str = sprintf([...
    '<!DOCTYPE html>\n',...
    '<html lang="en">\n',...
    '<head>\n',...
        '<meta charset="UTF-8">',...        
        '<meta http-equiv="X-UA-Compatible" content="ie=edge">',...  
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',...
        '<title>%s</title>\n',...
        '<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">',... 
        '<style type="text/css">\n%s',...   
        '</style>\n',...                  
    '\n</head>\n',...
    '<body>',... 
    '%s\n</body>\n',...
    '</html>\n'],title,myCSS(),sprintf('%s\n',bodycell{:}));
end

function str = myCSS()
% Note >'< must be replaced with: >''<
css = {...   
    'html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,font,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td{margin:0;padding:0;border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent}body{line-height:1}ol,ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:;content:none}:focus{outine:0}ins{text-decoration:none}del{text-decoration:line-through}table{border-collapse:collapse;border-spacing:0}',...
    'html { min-height:100%; margin-bottom:1px; }',...
    'html body { height:100%; margin:5px; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#000; line-height:140%; background:#fff none; }',...
    'html body td { vertical-align:top; text-align:left; }',...    
    'h1 { padding:0px; margin:0px 0px 25px; font-family:Arial, Helvetica, sans-serif; font-size:1.5em; color:#d55000; font-weight:bold; line-height:100%; }',...
    'h2 { padding:0px; margin:0px 0px  8px; font-family:Arial, Helvetica, sans-serif; font-size:1.2em; color:#d55000; font-weight:bold; line-height:140%; border-bottom:1px solid #d6d4d4; display:block; }',...
    'h3 { padding:0px; margin:0px 0px  10px; font-family:Arial, Helvetica, sans-serif; font-size:1.2em; color:#000;    font-weight:bold; line-height:100%; }',...
    'p  { padding:0px; margin:0px 0px 20px; }',...
    'img { padding:0px; margin:0px 0px 20px; border:none; }',...
    'p img, pre img, tt img, li img, h1 img, h2 img { margin-bottom:0px; }',...    
    'table th { padding: 2px 8px 2px 0px; text-align:left; vertical-align:middle; font-weight:bold; }',...
    'table td { padding: 2px 8px 2px 0px; text-align:left; vertical-align:top; }',...
    'ul{',...
    '  border-left: 0px solid LightGray;',...
    '  padding:0em 0em 0em 0em;',...
    '  margin: 0em 0em 0em 0em;',...    
    '  list-style-position: inside;',...     
    '}',...
    '  li a:hover {',...
    '  background-color: DodgerBlue;',...  
    '}',...
    'li{',...
    '  padding:0em 0em 0em 1.5em;',...
    '  margin: 0em 0em 0em 0em;',...   
    '  text-indent:0em;',...     
    '  vertical-align: top;  ',...
    '}',...
    'li[data-type="Aspect"]{',...
    ' list-style-image:url(''data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABsSURBVDhPY+ALmvWfEgw2gBzw798/ygwAAYIGgOQIyQ8iA2CKicUwPWADYCFKCkY14O9fFAkQABmKDSCrA9EYXiAEkNWBaKIMQHYNTB3M1dRzASGALUxIMgAboJ4B2PFMKJ71nz8QQmPiWf8Bpk4m1IZbXTEAAAAASUVORK5CYII='');',...
    '}',...
    'li[data-type="Spec"]{',...background-image    
    '  list-style-image:url(''data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAB4SURBVDhPvY8LDoAgDEM9gfFqejw4K8PU2Dn88TM2aXBlvtBhXHzs8QZokYj0AaBHADKbn2cKWTFgmt0+HVIA+lgRgJxdXwEcasx/9AX2ssQpIITkwoo1+G33cF4q5MQ9wv4DsIbdw6mAFimA9Fp994K83U0G+7gCJFAbJL4EOTsAAAAASUVORK5CYII='');',...
    '}'...
    'li[data-type="MAspect"]{',...
    ' list-style-image:url(''data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAACWSURBVDhPpZANDkAwDEadQEQcDIcTP1edja/xNR3DwkuadWu9rYqyX8KfEMEXnHP/BCApaNpBCgBrKifYXwS2seqmULej5DirullyogLv/XEUC+5ygr2+gA25wW/0BbaYE7FgXaOCBXKOaC8CWC8jvME+yh4FvNnCviwBQTNltg+rCp4Qwf6fzrwKUiNYsl9whwq+xxI2z0wPCAfZKTUAAAAASUVORK5CYII='');',...
    '}',...
    'li[data-type="Node"]{',...  
    ' list-style-image:url(''data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAACSSURBVDhPpZIBDoQgDAT5/9t8EqBZw+AKlRidpDnaq0NtTFtK+584BV8JBSXndrqotfYbaymtGgjUqIhA4BdMAkCETL8InEcBzYTXHOWTYGwkH+tCeRf4mIwO1OkF5bcJdPYtgxb3S/B6iVGToK4o9nrKb4LoJnJiKQB/gP/9DMpDgdA02kf0acNS8IYu+B5pPwCr9BOEKePcagAAAABJRU5ErkJggg=='');',...
    '}'...
    'li[data-type="Entity"]{',...
    ' list-style-image:url(''data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABiSURBVDhPzZHBCcAgEATTk9XakzWdMoEDTVYxmkAG9nGrDqJHiCnv5BSsYGZ7AvhOQHeNgv4mUAdUB3SNoLcR1BqzFIxSwzx9A8Ujga/x/w7zu4/o+IE6CnopmOVHgvWkXAAwfHTj79aOiwAAAABJRU5ErkJggg=='');',...
    '}'...
    'pre, code { font-size:12px; }',...
    'tt { font-size: 1.2em; }',...
    'pre { margin:0px 0px 20px; }',...
    'pre.codeinput { padding:10px; border:1px solid #d3d3d3;}',...      
    '@media print { pre.codeinput { word-wrap:break-word; width:100%; } }',...
    'span.keyword { color:#0000FF }',...
    'span.comment { color:#228B22 }',...
    'span.string { color:#A020F0 }',...    
    'span.syscmd { color:#B28C00 }',...
    'hr   {border-color: black; height: 5px;}',...
    '.clt, .clt ul, .clt li {',...
    ' position: relative;',...
	'}',...
	'.clt ul {',...
	'	list-style: none;',...
	'	padding-left: 0px;',...
	'	list-style-position: inside;',...
	'	//list-style: none;		',...
	'}	',...
	'.clt li::before, .clt li::after {',...
	'	content: "";',...
	'	position: absolute;',...
	'	left: 26px;',...
	'}	',...
	'.clt li::before {',...
	'	border-top: 1px solid;',...
	'	top: 7px;',...
	'	width: 10px;',...
	'	height: 0px;',...
	'}	',...
	'.clt li::after {',...
	'	border-left: 1px solid;',...
	'	height: 100%;',...
	'	width: 0px;',...
	'	top: -4px;',...
	'}	',...
	'.clt ul > li:last-child::after {		',...
	'	height: 12px;',...
	'	top: -4px;		',...
	'}	',...
	'.clt ul > li:first-child::before {	',...	
	'	border-top: none;		',...
	'}	',...
	'.clt ul > li:first-child::after {	',...	
	'	top: 2px;',...
	'	height: 0px;	',...
	'}	',...
};
str = sprintf('\t%s\n',css{:});
end

function str = GenTree(ischild,ses,Node)
%data-type="entity" "aspect" "spec" "dnode" "maspect"
CMap = ses.nodes;
if ischild
    add = {'<li>','</li>'};
    BORDER = ''; %use default
else
    add = {'',''};
    BORDER = 'style="border-style:hidden;"';
end
    
cstr = '';
for i = Node.children
    CNode = CMap([Node.treepath,'/',i{1}]);    
    cstr = sprintf('%s\n',cstr,GenTree(1,ses,CNode));
end

TYPE = Node.type;
if strcmp(TYPE,' ')
    TYPE = 'Node';
end
NAME = Node.name;
PATH = Node.treepath;
COLR = '#000';
FONT = 'normal';

for k =1:size(ses.Selection_Constraints.Pathes,1)
    if strcmp(PATH,ses.Selection_Constraints.Pathes(k))
        COLR = ses.Selection_Constraints.Color{k};
        FONT = 'bold';
        break
    elseif ismember(PATH,ses.Selection_Constraints.Pathes{k,2})
        COLR = ses.Selection_Constraints.Color{k};
        break
    end
end
str = sprintf('%s<ul %s><li data-type="%s"><a href="#%s"; style="text-decoration: none; vertical-align:top; font-weight:%s; color:%s">%s</a></li>%s</ul>%s',...
    add{1},BORDER,TYPE,PATH,FONT,COLR,NAME,cstr,add{2});
end

function str = GenSESFun(Fcns)

str = '';
for k = Fcns'
    FCN = k{:};
    if ~isempty(FCN.Filename)
        str = sprintf('%s<details><summary>%s</summary><pre class="codeinput">%s</pre></details>',...
        str,FCN.Filename,sprintf('%s\n',FCN.Data{:}));
    end
end


% Mark KeyWords:
for keyWord = {'function ','end','for ','while ','if ','else','elseif ','parfor ','return','break'}
    str = strrep(str,keyWord{:},['<span class="keyword">',keyWord{:},'</span>']); 
end

% Mark Strings:
str = regexprep(str,'''[\w ]*''','<span class="string">$0</span>');

% Mark Comments:
str = regexprep(str,'%+[^\n]*','<span class="comment">$0</span>');

% Mark SystemCommand:
str = regexprep(str,'![^\n]*','<span class="syscmd">$0</span>');
end
