classdef contextHelp < DefSett
    
methods
    function obj = contextHelp(MsgID)
        [Info,Expl] = getHelpText(MsgID);
        
        fig = figure(...
            'Name',                 'Context Help',...
            'NumberTitle',          'off',...
            'MenuBar',              'None');
        
        VBox = uiextras.VBox(...
            'Parent',               fig,...
            'BackgroundColor',      obj.Color.BG_P,...
            'Spacing',              5,...
            'Padding',              5);        
                
        uicontrol(...
            'Parent',               VBox,...
            'BackgroundColor',      [1 1 1],...
            'Style',                'edit',...                  
            'Max',                  60,...
            'Enable',               'inactive',...
            'HorizontalAlignment',  'left',...
            'String',               Info)
        
        if ~isempty(Expl)            
            uicontrol(...
                'Parent',               VBox,...
                'BackgroundColor',      [1 1 1],...
                'Style',                'edit',...                  
                'Max',                  60,...
                'Enable',               'on',...
                'HorizontalAlignment',  'left',...
                'String',               Expl)         
        end
        
        IconObj = JBttn(VBox,'ok','Insert Variable');
        set(IconObj.hnd,'MouseClickedCallback', 'close(gcf);');
        
        if isempty(Expl)
            set(VBox,'Sizes',[-1 23])
        else
            set(VBox,'Sizes',[-.7 -.3 23]) 
        end
    end
end
end

function [Info,Expl] = getHelpText(identifier)
%special signs (\n newline \t tab ,... can be used)
Infos = {...
    ['NAME and VALUE of an ENTITY ATTRIBUTE\n\n',...
     'Name has to be AlphaNumeric\n',...
     '(Note: >mb< is reserved for a ModelBase Link)\n\n',...
     'Value can be of TYPE \n',...
     '-''STRING'' \n',...
     '-[NUMBER] \n',...
     '-BOOL \n',...
     '-{CELLARRAY} \n',...
     '-STRUCT \n',...
     '-SESVAR \n',...
     '-SESFUN\n',...
     '(Some DataTypes can be combined if needed, see examples below)'],... %Entity Attributes
     ...
    ['Specrule \n\n',...
     'in case of severel childreen a rule for there selection have to be defined\n\n',...
     'usually the decision is made based on the value of a SESVAR\n',...
     'if CONDISTION1 is true --> SpecChild1\n',...
     'if CONDISTION2 is true --> SpecChild2\n',...
     '(Note: only one condition at a time has to be valid)\n\n',...
     'MATLAB inbuild functions ca be used (see example below)'],... %Specrule
    ...
    ['Aspecrule \n\n',...
     'in case of several aspects a rule for there selection have to be defined\n\n',...
     'usually the decision is made based on the value of a SESVAR\n',...
     'if BOOL CONDISTION1 is true --> AspectName1\n',...
     'if BOOL CONDISTION2 is true --> AspectName2\n',...
     '(Note: only one condition at a time has to be valid)\n\n',...
     'MATLAB inbuild functions ca be used (see example below)'],... %Aspectrule
    ...
    ['Global Priority\n\n',...
     'A global Priority which is used for complet pruning to ',...
     'resolve open decisions in case of specialisation'],... %AspPriority
     ....
    ['Couplings\n\n',...
     'to define a coupling you can ether use a SESFUN or use a static Coupling \n\n',...
     'the return value of a SESFUN must be a CELLARRAY with size n x 4 \n',...
     'each line is decribing one coupling relation with:\n',...
     '{''SourceName'',''SourcePortName'',''TargetName'',''TargetPortName''}\n',...
     'please see comlpete documentation for more infomation\n\n',...
     'when a SESFUN is used for MULTIASPECT Coupling two additional VARS can be used:\n',...
     'Parent     \t curent Name of the Parent\n',...
     'Childreen  \t list of all childreen names'],... %Couplings
    ...
    ['NAME and VALUE of an SES VARIABLE\n\n',...
     'Name has to be AlphaNumeric\n',...
     '\n',...
     'Value can be of TYPE \n',...
     '-''STRING'' \n',...
     '-[NUMBER] \n',...
     '-BOOL \n',...
     '-{CELLARRAY} \n',...
     '-STRUCT \n',...
     '-SESVAR \n',...     
     '(Some DataTypes can be combined if needed, see examples below)'],... %SESVAR
    ...
    ['Sematic Condition\n\n',...
     'a set of conditons which is used to determine if a set of SESVAR is valid for pruning\n',...
     'also can be used to define addional axioms for a SES\n\n',...
     'MATLAB inbuild functions ca be used (see example below)'],... %Semantic Condition
    ...
    ['Selection Constraints\n\n',...
     'are usually used to force a selection at a SpecNode instead of defining a additional condition\n',...
     'please see comlpete documentation for more infomation'],... %Selection Constraints
    ...
    ['SES Functions\n\n',...
     'are usually used to define procedural knowledge\n',...
     'SES Function can be used in different ways, for example to define couplings between nodes\n\n',...
     '(Note: MATLAB inbuild functions can be used without importing them)']}; %Functions

Expls = {...
    ['ATTRNAME:  \tMyAttr \tMyAttr1 \tMyAttr_2\n',... 
     'STRING:    \t''Hello World''\n',...
     'NUMBER:    \t3.1415 \t[4, 3.1415]\n',...
     'BOOL:      \tSESVAR<1 \t0 & 1\n',...
     'CELLARRAY: \t{4, 5, 6}\n',...
     'STRUCT:    \tstruct(''a'',4,''b'',5)\n',...
     'SESVAR:    \tMySESVAR\n',...
     'SESFUN:    \tMySESFUN(inArg1,InArg2,...)'],... %Entity Attributes
     ...
    ['SESVAR == 1 \n',...    
     'SESVAR == 2 & SESVAR2 == 3\n',...
     'strcmp(SESVAR,''StringA'')'],...%Specrule
    ...
    ['SESVAR == 1 \n',...    
     'SESVAR == 2 & SESVAR2 == 3\n',...
     'strcmp(SESVAR,''StringA'')'],... %Aspectrule 
    ...
    '',...%AspPriority
    ...
    ['Case ASPECT:\n',...
     '-COUPLING_SESFUN\n',...
     '-COUPLING_SESFUN(''String'',SESVAR,[1 2 3])\n\n',...
     'Case MULTIASPECT:\n',...
     '-COUPLING_SESFUN(Parent,Childreen,InputArgs)'],... %Couplings
    ...
    ['VARNAME:   \tMySESVAR \tMySESVAR1 \tSESVAR_2\n',... 
     'STRING:    \t''Hello World''\n',...
     'NUMBER:    \t3.1415 \t[4, 3.1415]\n',...
     'BOOL:      \tSESVAR<1 \t0 & 1\n',...
     'CELLARRAY: \t{4, 5, 6}\n',...
     'STRUCT:    \tstruct(''a'',4,''b'',5)\n',...
     'SESVAR:    \tMySESVAR\n'],... %SESVAR
    ...
    ['SESVAR == 1 \n',...    
     'ismember(SESVAR,[1,2,3])\n',...
     'strcmp(SESVAR,''StringA'')'],... %Semantic Condition
    ...
    '',... %Selection Constraints
    ...
    ''}; %Functions
    

Info = sprintf(Infos{identifier});
Expl = sprintf(Expls{identifier});
end